### ISSUE TITLE
Manual: The Voron Belt Path link

### ISSUE THREAD

**Issue by MallocArray** [VoronDesign/Voron-Trident#106]
Page 119
In the middle of the page is a URL address about CoreXY that is formatted as a link, and hovering over the text in the Edge browser PDF viewer changes the cursor, but no link address is specified and clicking on it does not result in opening the address. 

Manually typing the address does take you to a valid site, but it is not properly formatted as a link in the PDF

Same behavior in Edge and Adobe Acrobat Reader

**Comment by MallocArray** [comment]
In the most recent manual version this issue is still present in Edge in Windows 11

**Comment by ChopperRob** [comment]
Same issue with the "Hall Effect Endstop" link on page 137
