### ISSUE TITLE
X Carriage Frame, Belt Bolts conflicting with extruder asembly.

### ISSUE THREAD

**Issue by MadsGadeberg** [VoronDesign/Voron-Trident#11]
Hi Voron Team.

It seems that the bolt head is only recessed by 2,2mm.
![image](https://user-images.githubusercontent.com/7197181/130610323-4ab62036-6c99-4481-9f97-abc4dcea8de9.png)

![image](https://user-images.githubusercontent.com/7197181/130610472-259385f0-08ac-4c90-8f76-615d50c9105c.png)
![image](https://user-images.githubusercontent.com/7197181/130610603-a0c08d28-9d36-4957-b302-f84d5f18dbea.png)

SHCS M3 bolts require 3mm to be flush installed.
![image](https://user-images.githubusercontent.com/7197181/130610518-92e86c37-3c83-4217-bfc5-6ffa561f6531.png)
![image](https://user-images.githubusercontent.com/7197181/130610554-82c55d01-a3b7-464a-bd8b-993748beaf8c.png)

The Extruder assembly is the Galileo type but the backplate should be the same on where the issue is.

**Comment by eddietheengineer** [comment]
Thanks for letting us know! The Clockwork motor plate has clearances for the screwheads so they don't intersect:

<img width="522" alt="Screen Shot 2021-08-24 at 8 25 05 AM" src="https://user-images.githubusercontent.com/11861478/130615908-b6b744a0-a77d-4c40-82ff-e5ea2cdaf43f.png">

Galileo STLs generally aren't included with the stock Voron releases, so you will likely have to add a similar feature to the Galileo parts.

**Comment by MadsGadeberg** [comment]
Fuck me Eddie. Ty for the update end sorry for the sloppy issue.

A ton of ty for these projects by the way! i respect that!

**Comment by eddietheengineer** [comment]
If you can open the CAD--it's always possible that the Galileo CAD with a tweaked motor plate is in the assembly (maybe hidden). I'm not positive but it might be there!

**Comment by MadsGadeberg** [comment]
Ill check and leave the result in the comments for others to see.

**Comment by MadsGadeberg** [comment]
I used an early version of the Galileo Extruder which didnt have the groves shown on the picture. 
Feel free to close the issue and many ty for help!
![image](https://user-images.githubusercontent.com/7197181/130620733-b3521355-d0b5-4a19-b20c-5908910898e5.png)
