### ISSUE TITLE
Proble and nozzle clearance to small

### ISSUE THREAD

**Issue by MadsGadeberg** [VoronDesign/Voron-Trident#12]
Hi Voron Team.

I have assembled the Trident MGN12 assembly on my 2.4.

The clearance between the Probe and nozzle is causing me issues. I looked in both the Afterburner CAD and the Trident CAD to se the difference. Here is what i found:

The new MGN12 leaves 1mm of clearance:
![image](https://user-images.githubusercontent.com/7197181/130618785-735db8a8-6b13-404e-bec6-29090723123e.png)

The Old Afterburner leaves around 3mm of clearance:
![image](https://user-images.githubusercontent.com/7197181/130618878-898cacd7-6afd-4888-9061-77c5779d4fae.png)

My build:
The probe is a bit deformed by the heat but the left and back part shows the original shape. I could maby install the probe a tiny bit higher but it does not solve my problem.
![image](https://user-images.githubusercontent.com/7197181/130619631-6432c10e-6c12-411e-bc20-3bab4c43a017.png)
![image](https://user-images.githubusercontent.com/7197181/130619690-bf2e659c-f5c2-46ff-99e9-94199b35c46b.png)

It seems that the clearance of 1mm is a bit to small to account for assembly tollerances.

**Comment by eddietheengineer** [comment]
Yes--this is one of the tradeoffs for the MGN12 axis, you need a different probe as shown here:

<img width="763" alt="Screen Shot 2021-08-24 at 8 57 33 AM" src="https://user-images.githubusercontent.com/11861478/130620428-0ee3aecf-1d68-41ad-97f1-342cbfcf325b.png">

The PL-08 was likely kept in CAD as a reference to show that it wasn't practical to use

**Comment by stvptrsn** [comment]
Technically, the PL08 _should_ work if you have a Mosquito hotend.  But it's easier to recommend moving away from the PL series.

**Comment by MadsGadeberg** [comment]
I have pushed the PL up as far as i can and it is just enough. I reckon i have below 0,5mm of clearance which is above 0.
