### ISSUE TITLE
Thumb bolt/ Knurled nut wrong size in manual?

### ISSUE THREAD

**Issue by Faenum** [VoronDesign/Voron-Trident#120]
The knurled nut/thumb screw for the bed on the manual says M4 (and thats what has come in the kit) But every other part (screws/tnuts etc) are all M3 and none of it wants to fit together. 
Is the manual wrong in that it should be an M3 knurled nut/thumbscrew?

**Comment by timmit99** [comment]
Nope, the manual is correct. That m4 nut is used as a spacer. You don't actually thread into it but it just acts as a spacer to stand the bed off of the extrusions.

**Comment by Faenum** [comment]
Thanks
In that case the bolts are too short. It says m316 but theyre not long enough to reach the Tnut

**Comment by Faenum** [comment]
We worked it out, the LDO kit does come with a thicker bed that needs M3x20

**Comment by ccfman2004** [comment]
The Build Plate PDFs mention a bed thickness of 6.5mm to 9.5mm thick which means the M3x16 bed screws are too short if your bed is thicker than 6.5mm. The manual should mention you need M3x20 if your bed is 9.5mm thick as many beds from the recommend US online resellers are 9.5mm thick.

**Comment by Faenum** [comment]
Yeah, I couldnt find anything in the manual about that, just says use m3x16 screws. It could be written elsewhere though.
