### ISSUE TITLE
Manual should instruct that T-nuts be preloaded prior to frame assembly

### ISSUE THREAD

**Issue by kozross** [VoronDesign/Voron-Trident#157]
The fact [this video even exists at all](https://www.youtube.com/watch?app=desktop&v=hpkN9NHoKiY) suggests that many people find it difficult to load T-nuts into extrusions with the frame already assembled. It wouldn't be difficult to make this preloading the first step, before assembling the frame, and would save people (including me!) a lot of frustration. I'm basically gonna have to take apart my frame, which I spent no small amount of time squaring, because I will need to preload T-nuts, and I'd rather save future builders the hassle.

Alternatively, the manual should clearly specify how you are supposed to load T-nuts into an already-assembled and squared frame, as it currently fails to do that.

**Comment by JustAManDoingGit** [comment]
The point of that nut is to be a drop-in installation of nut (not needing to preload it). The problem seems more like a mismatch of nut used for your specific extrusion. I never really had problem installing those.
