### ISSUE TITLE
X Carriage Hex Hole Rounded

### ISSUE THREAD

**Issue by crashmaxx** [VoronDesign/Voron-Trident#17]
![x_carriage_frame](https://user-images.githubusercontent.com/34484735/135109289-d8b35d7e-8a05-42dc-945d-e54d7d5308e9.PNG)

I noticed the bottom hex nut hole has a round cut going into it some depth.

Since all the other carriages have plain hex holes for the nuts, I'm guessing this is an error. It's an easy fix and I don't mind putting in a pull request, but I wanted to check if someone might have intentionally made it that way first.

The same also applies to the V2.4 MGN12 mod.
[https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/arkeet/mgn12](url)

**Comment by bdbell** [comment]
The rounded area is to allow for the insertion of a 6x3 magnet to use with the Hall effect end stops.

**Comment by crashmaxx** [comment]
> The rounded area is to allow for the insertion of a 6x3 magnet to use with the Hall effect end stops.

I didn't realize that. No problem, I'll close this.
