### ISSUE TITLE
Horizontal Line keep repeating (Voron Trident 250)

### ISSUE THREAD

**Issue by Daehyoun** [VoronDesign/Voron-Trident#172]
Interesting symptom....
In my rectangular lithophane printing, my new Voron Trident 250 printer has some strange issue.

Certain layer was shifted and this symptom happens at every  3~3.5mm
Printer is Voron Trident 250 and just assembled and started to print and test it.
I thought CoreXY bed will not shifted horizontally, and there will not be this issue.
But, happened....

Any idea to try to improve this issue?

Thanks

Daehyoun

![image](https://github.com/user-attachments/assets/6ae3378e-e4c7-4d27-bb8c-730f89c7384f)
![image](https://github.com/user-attachments/assets/7b6f4e2e-c14f-4be6-9b9c-4de118aeeb3d)

**Comment by nemgrea** [comment]
this would be perfect for a help ticket on the discord or a post on the forum to get help from the community. it looks like this is a user specific issue and not a printer design issue.
