### ISSUE TITLE
M5 bolts on XY joints are chamfered instead of bridged

### ISSUE THREAD

**Issue by henrikssn** [VoronDesign/Voron-Trident#22]
This is originally for the V2, but it was suggested in the engineering ticket on Discord to submit the issue for Trident since it has the most recent gantry.

Issue: The recess for the M5x40 BHCS bolts in the XY joints are chamfered. This causes the bolts to slowly creep for me, which means I continuously need to re-tighten them

Fix: I used the "bridging trick" which resolved the creeping.

I'm happy to contribute my fix if possible.

**Comment by timmit99** [comment]
Chambered? Do you mean chamfered?

**Comment by henrikssn** [comment]
> Chambered? Do you mean chamfered?

Correct, I fixed the title/description (sorry, I'm not a native speaker)

**Comment by BerzerkaDurk** [comment]
I believe this was addressed in the R1 update

**Comment by stvptrsn** [comment]
Yep, I must have forgotten to link the issue.  Thanks!

**Comment by BerzerkaDurk** [comment]
You betcha. Great job with the update.

**Comment by james5843** [comment]
For anyone who doesn't know what the cross bridge method it like I did, [this video](https://www.youtube.com/watch?v=W8FbHTcB05w) outlines it in detail. A cool design technique!
