### ISSUE TITLE
MGN 12 trident.

### ISSUE THREAD

**Issue by selimayaz** [VoronDesign/Voron-Trident#26]
Hello not an issue but i wonder anyone made or have MGN12 design for this printer?

**Comment by stvptrsn** [comment]
Hi @selimayaz your best chance for any information on modifying the design will be at the Voron Discord.  MGN12 for the Y and Z rails poses a problem in that the MGN12 cartridges are wider than the 2020 frame extrusions so would rub on the enclosure panels.
