### ISSUE TITLE
Corrections for manual

### ISSUE THREAD

**Issue by koonweee** [VoronDesign/Voron-Trident#3]
This issue can be used to track all neccessary corrections to the manual.
Please add any corrections as a new comment :-)
![image](https://user-images.githubusercontent.com/34903259/129510101-bcb068de-2b34-47e0-9868-6c650254a677.png)
^ contributed by Vapour3D Samuel#5741

**Comment by mhoush** [comment]
On page 16 there's a label that says "PEPARE 8 EXTRUSIONS" rather than "prepare".

**Comment by Yeriwyn** [comment]
Page 44, is there any way to highlight the m3, because with the m5 everywhere it’s easy to miss, and 3 and 5 do look similar

**Comment by DunarDolorgiet** [comment]
Feel free to add annotation to https://assets.adobe.com/id/urn:aaid:sc:US:0f574b90-97b2-4771-a208-91fdc6357ab5?view=published

**Comment by mhoush** [comment]
Transferred comments over there, cheers!
