### ISSUE TITLE
Broken hyperlinks within the Assembly Manual

### ISSUE THREAD

**Issue by simonrwatts** [VoronDesign/Voron-Trident#30]
1) Link on page 121 doesn't work due to a space in the text of the link after link/ 

2) On page 248 of the Assembly Manual one of the links is broken. https://voron.link/m6wtwnl

It's in this text on the page:
If you are using a “FYSETC mini12864” please review section 3.3 of the FYSETC Spider documentation (https://voron.link/m6wtwnl).

Note: I just did a search for voron.link within the PDF and tested all the links, the rest are currently working.

**Comment by BerzerkaDurk** [comment]
Weird. It works for me.
