### ISSUE TITLE
Manual (page 53) needs to point out offset of vertical extrusion

### ISSUE THREAD

**Issue by mikem1017** [VoronDesign/Voron-Trident#34]
As a first time voron builder, I found this page to not be clear enough that the vertical extrusion will then be offset from the horizontal extrusion, and in which way (in or out) from the extrusion.  After some questions on the discord, I have found that other folks believe this to not be 100% clear either.

Thus I would like to propose a "red circle" around the corner piece highlighting the outward (way from the print bed) offset of the vertical extrusion relative to the horizontal extrusion.

**Comment by jarrettv** [comment]
I've seen this asked multiple times over the past few months in discord. So include the answer in the manual as well: the offset is for the belts which are routed behind the extrusion
