### ISSUE TITLE
Missing Value for BOM (M3 T-nut) in Configurator

### ISSUE THREAD

**Issue by Vapour3D-Samuel** [VoronDesign/Voron-Trident#4]
Missing Value for BOM (M3 T-nut) in Configurator

The BOM in the Configurator shows NaN for the M3 T-nuts

![image](https://user-images.githubusercontent.com/11615390/129511331-0274f2b3-1bd1-421e-a95f-713beed88ab1.png)

**Comment by stvptrsn** [comment]
Thanks for the report.  We are aware that the configurator is not accurate right now.  Although if you have the link you can view it, the page isn't yet published.  We're working on it and will post an announcement on Discord when it is live.

**Comment by Vapour3D-Samuel** [comment]
Great, thank you guys again!

**Comment by DunarDolorgiet** [comment]
Fixed
