### ISSUE TITLE
Squaring instructions note to move the gantry to A and B drives to square.  B drive has protruding Y endstop bracket.

### ISSUE THREAD

**Issue by mobilemcclintic** [VoronDesign/Voron-Trident#43]
In the manual on page 118, we are instructed to move the gantry back to the A/B drives to square the gantry.  The gantry hits the Y endstop block before hitting the A/B drives.  This makes the travel on the right side shorter than the left and had me wondering how in the world I could rack the gantry but always have the left side not be the one stopping.

**Comment by mobilemcclintic** [comment]
![2021-12-19 11_35_36-Autodesk Fusion 360 (Personal - Not for Commercial Use)](https://user-images.githubusercontent.com/47824980/146688828-c7c5e7e5-68d6-48c5-adcd-958ba5ac379e.png)

**Comment by j-heffron** [comment]
The change in the assembly manual noting to rack the gantry to the front idlers rather than the AB drive motor assemblies appears to have been reverted by #68. As far as I can tell, there has not been any change to the y endstop bumper part to warrant reverting the instructions.
