### ISSUE TITLE
Electronics Bay File Naming Convention

### ISSUE THREAD

**Issue by Annex-Engineering** [VoronDesign/Voron-Trident#5]
Seems as if the electronics bay brackets use a different naming convention to the standard file structure, as when compared to the rest of the repo. Maybe remove the 2pc part, or something?

This may cause confusion to end users, especially legacy ones

Congrats on your release!
 - Trails

**Comment by FHeilmann** [comment]
They're named "2pc" because the STL contains both parts of the mount, so the names are, in fact, correct.

-FH

**Comment by Annex-Engineering** [comment]
I get that, just stating that it may be worth a comment in the file naming convention if your going to adopt this as a standard to prevent confusion with end users, 

x# = print quantity
#pc = multiple parts in same file, etc

**Comment by FHeilmann** [comment]
We'll keep it in mind if it comes up in the future. 

Thanks for bringing it up

-FH
