### ISSUE TITLE
Cannot Download the .STL files for A or B Drive Frame Lower - Both files appear to be corrupted.

### ISSUE THREAD

**Issue by Rwhite692** [VoronDesign/Voron-Trident#53]
When attempting to download the STL files for the A and B drive Frames (Only the Lowers), Clicking "Download" on either of these two files, results in no download initiated, just a display of a raw ASCII text file.
![driveunits](https://user-images.githubusercontent.com/98500161/151272381-5d72278c-18e5-4b14-b84d-069b648b653c.jpg)

**Comment by raymondh2** [comment]
STLs can be binary or ASCII. Right-click and save as

**Comment by Rwhite692** [comment]
Thanks Raymond, I tried that, however these two .STLs will not open in Cura...returns an error message (File is either corrupt, or contains no model data). I even fired up F360 to see If I could import them, with no luck (Was thinking I could import as ASCII / Export them as Binary .stl) ....I am not well versed in dealing with ASCII .stl files so I'm kind of at a loss here...

**Comment by Rwhite692** [comment]
Hi Raymond, FYI, I figured it out, and I should have occurred to me.... Windows was adding a hidden extra ".txt" extension after the ".stl" extension (creating filename.stl.txt, with the .txt being conveniently invisible). Newer laptop and never thought to check this. Best Regards, -Rob
