### ISSUE TITLE
Spider v2.2 interference with mount

### ISSUE THREAD

**Issue by poernahi** [VoronDesign/Voron-Trident#57]
The spider mount provided could not be fully secured to v2.2 board due to interference with fuse F7 under the terminal blocks.

**Comment by poernahi** [comment]
![A21B82E0-046E-42CE-B9D7-F1B4F66D87FE](https://user-images.githubusercontent.com/10459441/155058259-43f4e8d6-a40a-40bd-9411-85915bb9755c.jpeg)

**Comment by stvptrsn** [comment]
Yep, that stupid fuse they added after the Spider v1.  THis will be fixed in the next Trident release.  In the meantime the V2.4r2 files has an updated mount.  Alternatively you can rotate the mount 180 degrees to clear the fuse.
