### ISSUE TITLE
Wrong position of heat set insert hole on front_skirt_b_350

### ISSUE THREAD

**Issue by Promix953** [VoronDesign/Voron-Trident#62]
![front_skirt_b_350.stl](https://user-images.githubusercontent.com/22642692/155757696-73cb405c-0af2-4984-b4ae-13be680620ba.png)
![CAD](https://user-images.githubusercontent.com/22642692/155758181-c89a2eb0-b46b-40b5-bad2-6fe1c41e169a.png)

**Comment by stvptrsn** [comment]
Thanks for the report.  I'll include it in the next release.   The problem is opposite of what you expect though.  It's actually side A that's wrong :)
