### ISSUE TITLE
Corrections for configurator generated BOM

### ISSUE THREAD

**Issue by koonweee** [VoronDesign/Voron-Trident#7]
![image](https://user-images.githubusercontent.com/34903259/129675850-d4141eb5-8d7c-44a2-bc86-c49da33ef01b.png)
Fork crimp terminals are not included

**Comment by Kosh42** [comment]
Also, no M3 nylon lock nuts specified but they are called for on P78.

**Comment by BerzerkaDurk** [comment]
> 

![image](https://user-images.githubusercontent.com/81716812/170847249-0a053d83-54f2-4ef4-adf6-e2c00ac4aecc.png)

**Comment by nemgrea** [comment]
> ![image](https://user-images.githubusercontent.com/34903259/129675850-d4141eb5-8d7c-44a2-bc86-c49da33ef01b.png) Fork crimp terminals are not included

how many for terminals are needed?

**Comment by nemgrea** [comment]
no response
