### ISSUE TITLE
manual inverted G and F Extrusion 

### ISSUE THREAD

**Issue by Frigolol** [VoronDesign/Voron-Trident#70]
seems like page 147 is pointing G as F and F as G extrusion

**Comment by BerzerkaDurk** [comment]
Clips from the manual, for clarity. 

According to the diagram on pg 13, the G extrusion is the long front bed support extrusion, and F is the short center bed extrusion.

![image](https://user-images.githubusercontent.com/81716812/169713989-776521fc-277c-403b-bd34-d7246370ea10.png)

pg 147 has them labeled backward

![image](https://user-images.githubusercontent.com/81716812/169714117-1319b123-acfc-4090-8d17-15a9a32711b4.png)
