### ISSUE TITLE
README discrepancy. Build of Material vs Bill of Material 

### ISSUE THREAD

**Issue by dougshell** [VoronDesign/Voron-Trident#74]
The readme states that you can find the "build of materials", but I believe this should read as "bill of materials". "Web site" is most often spelled as one word as well, but this isn't as big of an issue. The two-word variant is possibly influenced by the word "web page"

I know everyone wants to contribute to the VORON project and be well compensated. I'll take my payment in either Voron parts or thoughts and prayers!!!

"# Voron Trident

![Image of Voron Trident](https://vorondesign.com/images/voron_trident.jpg)

The official release of the Voron Trident 3D printer.  You can find the Build of Materials in the configurator located at the [Voron Design]( http://vorondesign.com/voron_trident) web site.  The recommended sizes for this printer are 250x250x250, 300x300x250 and 350x350x250."

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Trident/pull/85
