### ISSUE TITLE
[Manual] Missing items and corrections

### ISSUE THREAD

**Issue by rh101** [VoronDesign/Voron-Trident#76]
Page 216: "Power Inlet" title is not aligned correctly, so it is off the page.

Page 217: Roll-in M3 nuts are missing from the diagram for the power inlet printed part mounting to the frame.

Page 232: Controller board jumper settings steps 3 and 4 do not match the highlighted section of the board.  They should be switched around.  In the diagram, 3 is the probe voltage setting, and 4 is the fan section.

**Comment by iitsalex** [comment]
![image](https://user-images.githubusercontent.com/20635452/190937223-a1e00e7f-36a6-47ff-a9a6-586552af789c.png)
Page 13 also has a typo on "Length"
