### ISSUE TITLE
Manual and BOM disagree on M3 FHCS with Power Inlet mounting

### ISSUE THREAD

**Issue by wrwindsor** [VoronDesign/Voron-Trident#80]
Manual on page 216 (Power Inlet) says to use two M3x10 FHCS.

M3x10 FHCS doesn't exist in the BOM.

M3x12 will work here, even if a touch too long for appearances, and M3x12 FHCS is in the BOM.

Dunno if BOM or Manual issue.

**Comment by nemgrea** [comment]
bom change submitted
