### ISSUE TITLE
Voron trident losing communication with mcu and ends the print after 50+ minutes

### ISSUE THREAD

**Issue by piertek** [VoronDesign/Voron-Trident#89]
Hi, I'm having issues with printer quirting printing at random time, sometimes after 50 min some  after 2 hours, today just now it stopped twice on different prints, the screen loses the image on the tft and the connection with mainsail shows this: Klipper reports: 
SHUTDOWN
Lost communication with MCU 'mcu'
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown.
i have being told last week that it was a usb connection problem so i search for it and changed the usb, yesterday night we updated Moonraker dependencies and today the first fail was after 2 something hours.
is a voron trident 300, running huvud canbus
i have being tracing temperatures from all mcu's and the highestone is the huvud topping at 70 degrees celsius printing abs in enclosure.
All i can understand from the logs is that klipper has shutdown.
Any help will be appreciated im desperate.
[klippy (26).log](https://github.com/VoronDesign/Voron-Trident/files/10198736/klippy.26.log)
[moonraker (20).log](https://github.com/VoronDesign/Voron-Trident/files/10198737/moonraker.20.log)

**Comment by raymondh2** [comment]
Hello! Thanks for reaching out to us on GitHub. We use GitHub for managing design issues not troubleshooting. Try one of our other community sites below for troubleshooting help.

Discord: https://discord.gg/voron
Official Forum: https://forum.vorondesign.com/
Reddit: https://www.reddit.com/r/vorondesign/
