### ISSUE TITLE
Terminology Mismatch between BOM, Assembly Manual and sourcing guide

### ISSUE THREAD

**Issue by chaos777b** [VoronDesign/Voron-Trident#93]
The Voron Assembly manual calls for a M5 Shim when putting together the A idler, page 26.
The generated BOM for the trident does not have an M5 Shim, but it does have an M5 1mm Spacer.
The souring guide list it as M5 1.0mm Thick Shim/Washer.

Side note the LDO kit has both precision M5 1mm spacer, and a M5 1mm washer.

Yay for terminology!

**Comment by nemgrea** [comment]
BOM and SG have been fixed, next manual update will consolidate all three, for now "shim" is mentioned in all three locations
