### ISSUE TITLE
Extrusion lengths, including for a 250mm frame, are missing in Assembly_Manual_Trident.pdf 

### ISSUE THREAD

**Issue by tkalbitz** [VoronDesign/Voron-Trident#95]
In the current manual of the Trident is the length for the different extrusions missing.  More precisely: The pages are missing. They were in the manual in the past see this "Steve Builds" stream: https://youtu.be/JWLwHDgkYPw?t=77

The lengths are needed to reference extrusions length and letters e.g on Page 13.  Additional on Page 13 in the manual is also a reference to the page "The length of marked extrusions depends on the build size. The size shown is for a 250 size Trident. Add 50/100mm for a 300/350 sized Trident."

**Comment by tkalbitz** [comment]
One possible solution could be to reference on page 13 to the configurator on the web page and add in the configurator after every extrusion a note "Extrusion 'A' in the manual xx mm".

**Comment by nemgrea** [comment]
they were replaced/removed intentionally by the current length diagram on page 13 due to the majority of the extrusion lengths being build size dependent.

the exact number measurements are not needed in order to organize the extrusion as it is shown on page 13
